{
 "title": "notifier_consumer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "put_consumer_status_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "put_consumer_status_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "post_notifier_consumer_weather_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "post_notifier_consumer_weather_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "post_notifier_consumer_logs_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "post_notifier_consumer_logs_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "post_notifier_consumer_alert_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "post_notifier_consumer_alert_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "delete_notifier_consumer_alert_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delete_notifier_consumer_alert_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "delete_notifier_consumer_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delete_notifier_consumer_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "post_notifier_consumer_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "post_notifier_consumer_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "consumer_weather_kafka_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_weather_kafka_call_summary_sum"
    }
   ]
  },
  {
   "title": "consumer_topic_weather_counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consumer_topic_weather_counter" }
   ]
  }
 ]
}