---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configMapName" . }}
  namespace: {{ .Values.namespace.name }}
data:
  DB_HOST_NOTIFIER: {{ .Values.DB_HOST_NOTIFIER | quote }}
  DB_NAME_NOTIFIER: {{ .Values.DB_NAME_NOTIFIER | quote }}
  BROKER1: {{ .Values.KAFKA_BROKER_A_svc  }}
  BROKER2: {{ .Values.KAFKA_BROKER_B_svc  }}
  BROKER3: {{ .Values.KAFKA_BROKER_C_svc  }}
  NOTIFICATION_LIMIT: {{ .Values.NOTIFICATION_LIMIT | quote }}