{
 "title": "poller_consumer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "post_consumer_alert_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "post_consumer_alert_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "delete_consumer_alert_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delete_consumer_alert_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "delete_consumer_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delete_consumer_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "put_consumer_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "put_consumer_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "post_consumer_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "post_consumer_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "consumer_watch_kafka_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_watch_kafka_call_summary_sum"
    }
   ]
  },
  {
   "title": "consumer_topic_watch_counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consumer_topic_watch_counter" }
   ]
  }
 ]
}