apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "ingressName" .}}
  namespace: backend-webapp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ template "webappDomainName" .}}
    secretName: webapp-kubernetes-tls
  rules:
  - host: {{ template "webappDomainName" .}}
    http:
      paths:
      - backend:
          serviceName: {{ template "serviceName" .}}
          servicePort: 80