apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.namespace.logging.name }}
  labels:
    app: {{ .Values.kibana.name }}
spec:
  type: {{ .Values.kibana.service.spec.type }}
  ports:
  - port: 80
    targetPort: 5601
    protocol: TCP
  selector:
    app: {{ .Values.kibana.name }}