kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.fluentd.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.fluentd.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fluentd.name }}
    namespace: {{ .Values.namespace.logging.name }}