{
 "title": "user_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "update_user_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_user_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "get_user_UA_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_user_UA_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "get_user_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_user_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "create_user_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "create_user_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "update_user_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "update_user_counter" }
   ]
  },
  {
   "title": "get_user_unauthenticated_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "get_user_UA_counter" }
   ]
  },
  {
   "title": "create_user_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "create_user_counter" }
   ]
  },
  {
   "title": "get_user_counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "get_user_counter" }
   ]
  }
 ]
}