{
 "title": "Watch webapp dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "delete_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delete_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "update_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "update_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "get_All_watches_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_All_watches_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "get_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "get_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "create_watch_database_call_summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "create_watch_database_call_summary_sum"
    }
   ]
  },
  {
   "title": "delete_watch_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "delete_watch_counter" }
   ]
  },
  {
   "title": "update_watch_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "update_watch_counter" }
   ]
  },
  {
   "title": "get_All_Watches_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "get_All_Watches_counter" }
   ]
  },
  {
   "title": "get_watch_counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "get_watch_counter" }
   ]
  },
  {
   "title": "create_watch_counter",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "create_watch_counter" }
   ]
  }
 ]
}