---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "configMapName" . }}
  namespace: {{ .Values.namespace.name }}
data:
  DB_HOST_POLLER: {{ .Values.DB_HOST_POLLER | quote }}
  DB_NAME_POLLER: {{ .Values.DB_NAME_POLLER | quote }}
  BROKER1: {{ .Values.KAFKA_BROKER_A_svc  }}
  BROKER2: {{ .Values.KAFKA_BROKER_B_svc  }}
  BROKER3: {{ .Values.KAFKA_BROKER_C_svc  }}
  WEATHER_POLL_TIME: {{ .Values.WEATHER_POLL_TIME | quote }}