---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dbsecretName" .}}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.DB_USERNAME | quote }}
  DB_PASS: {{ .Values.DB_PASS | quote }}

---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dockerregistrykeyName" .}}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "owsecretName" .}}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  OW_API_KEY: {{ .Values.OW_API_KEY | quote }}