---
aws_region: us-east-1
aws_profile: "{{ profile }}"
# VPC Information
vpc_name:       "jenkins-{{ aws_region }}-vpc"
vpc_cidr_block: 10.0.0.0/16
#subnet
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}a"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}b"
  private-3:
    cidr: 10.0.3.0/24
    az: "{{ aws_region }}c"
# Internet Gateway Name
igw_name: "IGW network"

# Security Groups
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22

